### ALL
GET http://localhost:1337/api/v1/trackables

### SINGLE
GET http://localhost:1337/api/v1/trackable/634480dda1a1af9f56fb4c1c

### ADD
POST http://localhost:1337/api/v1/trackables HTTP/1.1
content-type: application/json

{
  "type": "boolean",
  "settings": { "name": "New One" },
  "data": {}
}

### DELETE
DELETE http://localhost:1337/api/v1/trackable/43243ae6-abb7-4498-bedd-f420e5f5bb6a

### UPDATE
PUT http://localhost:1337/api/v1/trackable/634480dda1a1af9f56fb4c1c HTTP/1.1
content-type: application/json

{
  "year": 2022,
  "month": 1,
  "day": 12,
  "value": true
}

