### ALL
GET http://localhost:1337/api/v1/trackables

### SINGLE
GET http://localhost:1337/api/v1/trackable/1

### ADD
POST http://localhost:1337/api/v1/trackables HTTP/1.1
content-type: application/json

{
  "type": "boolean",
  "settings": { "name": "New One" },
  "data": {}
}

### DELETE
DELETE http://localhost:1337/api/v1/trackable/43243ae6-abb7-4498-bedd-f420e5f5bb6a

### UPDATE
PUT http://localhost:1337/api/v1/trackable/44f5046b-a67f-4301-be02-b49e7da6f323 HTTP/1.1
content-type: application/json

{
  "data": {
    "2022": {
      "09": {
        "08": false
      }
    }
  }
}
