FROM node:20-alpine AS base
 
FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

RUN npm install -g pnpm
RUN npm install -g turbo@^2
COPY . .
 
# Generate a partial monorepo with a pruned lockfile for a target workspace.
RUN turbo prune @tyl/server --docker
 
# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app
 
# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN npm install -g pnpm
RUN pnpm install
 
# Build the project
COPY --from=builder /app/out/full/ .
RUN pnpm turbo run build --filter=@tyl/server...
 
FROM base AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 tylrunner
USER tylrunner
 
COPY --from=installer /app/apps/server/package.json .
 
# Copy app build
COPY --from=installer --chown=tylrunner:nodejs /app/apps/server/.output ./output
COPY --from=installer --chown=tylrunner:nodejs /app/apps/server/.vinxi ./vinxi
# Copy drizzle folder. It will run migration on statup
COPY --chown=tylrunner:nodejs /packages/db/drizzle  ./drizzle
 
CMD ["node", "./output/server/index.mjs"]
