import Head from 'next/head';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="example">
        <h1 className="text-3xl font-bold underline">Hello</h1>
      </main>

      <footer>This is footer</footer>
    </div>
  );
}

export async function getServerSideProps() {
  //const res = await fetch(`http://localhost:3000/api`);
  //const json = await res.json();

  return {
    props: {},
  };
}
